### ISSUE TITLE
自荐信息源

### ISSUE THREAD

**Issue by chinesehuazhou** [tychozzz/gpt-rss#1]
厚脸皮自荐《Python潮流周刊》，最近包含不少AI、LLM、GPT相关的文章和项目

网址：https://pythoncat.top

RSS：https://pythoncat.top/rss.xml

标签：编程; Python; 开源; GPT;人工智能

**Comment by tychozzz** [comment]
好的，很强！这个看起来更适合 backend rss 项目，我将它移入这个项目吧，谢谢推荐！
