### ISSUE TITLE
网站 rss

### ISSUE THREAD

**Issue by yiranzhimo** [tychozzz/gpt-rss#4]
您好，非常感谢你的工作，请问能提供网站的 rss 地址吗？

**Comment by Pandolar** [comment]
Really need this

**Comment by tychozzz** [comment]
最近有点忙，过年时候我添加一下这个功能，谢谢反馈！

**Comment by realjustinwu** [comment]
+1

**Comment by Yam0214** [comment]
> 最近有点忙，过年时候我添加一下这个功能，谢谢反馈！

hey，这边也期待rss订阅功能

**Comment by h405u** [comment]
+1

**Comment by tychozzz** [comment]
已经添加了这个功能啦，有bug麻烦踢下我🙏

**Comment by tychozzz** [comment]
<img width="180" alt="image" src="https://github.com/tychozzz/gpt-rss/assets/73587471/b5d177af-9bbe-4c94-b30f-00b91ae843a9">
